# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0002_character_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('name_engine', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=1000)),
                ('durability', models.IntegerField(default=1000)),
                ('tank', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Engine_ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('name_engine', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=1000)),
                ('durability', models.IntegerField(default=1000)),
                ('tank', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Laser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('name_laser', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=1000)),
                ('durability', models.IntegerField(default=1000)),
                ('weight', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Laser_ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('name_laser', models.CharField(max_length=100)),
                ('power', models.IntegerField(default=1000)),
                ('durability', models.IntegerField(default=1000)),
                ('weight', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ship', models.CharField(max_length=100)),
                ('ship_class', models.CharField(choices=[('DR', 'DRAGUN'), ('HS', 'HeavyShip'), ('MD', 'Medical'), ('CG', 'CargoShip')], default='DR', max_length=3)),
                ('armor', models.IntegerField(default=400)),
                ('load', models.IntegerField(default=10000)),
                ('laser_count', models.IntegerField(default=1)),
                ('evasion', models.IntegerField(default=400)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Character.Character')),
            ],
        ),
        migrations.AddField(
            model_name='laser_ship',
            name='ship_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Character.Ship'),
        ),
        migrations.AddField(
            model_name='engine_ship',
            name='ship_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Character.Ship'),
        ),
    ]
