# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0003_auto_20170914_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='credits',
            field=models.IntegerField(default=1000),
        ),
    ]
