# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0005_auto_20170923_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
