# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Character', '0006_character_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='accurancy',
            field=models.IntegerField(choices=[(4, 'Four'), (6, 'Six'), (8, 'Eight'), (10, 'Ten'), (12, 'twelve')], default=4),
        ),
        migrations.AddField(
            model_name='character',
            name='defence',
            field=models.IntegerField(choices=[(4, 'Four'), (6, 'Six'), (8, 'Eight'), (10, 'Ten'), (12, 'twelve')], default=4),
        ),
        migrations.AddField(
            model_name='laser',
            name='mobility',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='laser_ship',
            name='mobility',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='engine',
            name='power',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='engine_ship',
            name='power',
            field=models.IntegerField(default=1),
        ),
    ]
