# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceMap', '0005_city'),
        ('Character', '0007_auto_20170926_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='planate_id',
            new_name='planet_id',
        ),
        migrations.AddField(
            model_name='engine',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceMap.City'),
        ),
        migrations.AddField(
            model_name='laser',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpaceMap.City'),
        ),
    ]
