# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('size', models.FloatField()),
                ('color', models.CharField(max_length=8)),
                ('temp', models.FloatField()),
                ('name_system', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
            ],
        ),
    ]
