# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceMap', '0004_auto_20170817_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=50)),
                ('inhabited', models.BooleanField(default=True)),
                ('space_port', models.BooleanField(default=True)),
                ('population', models.IntegerField(default=0)),
                ('city_status', models.CharField(choices=[('Vilage', 'Vilage'), ('Town', 'Town'), ('City', 'City')], default='Vilage', max_length=7)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpaceMap.Planet')),
            ],
        ),
    ]
